/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Approved_Source;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author tysonmauriceprice
 */
public  class Products extends javax.swing.JFrame {
    

Connection con;
Statement stmt;
ResultSet rs;
int curRow = 0;

    
    public Products() {
        initComponents();
        DoConnect();
        
    }
    
    
    public void DoConnect() {
       try {        
           //connection to the database
            String host = "jdbc:derby://localhost:1527/Products";
            String uName = "tyson";
            String uPass = "gaston";
            Connection con = DriverManager.getConnection(host, uName, uPass);
      
            //exectutes the sql and load the records into a resultset
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM PROD_DESC";
            ResultSet rs = stmt.executeQuery(sql);
            
                //move the cursor to the first record and aquire the data
            while (rs.next()) {  
                int UPC_Code_col = rs.getInt("UPC_Code");
                String UPC_Code = Integer.toString(UPC_Code_col);
                String Manu_Info = rs.getString("Manu_Info");
                String Date_Found = rs.getString("Date_Found");
                String EST = rs.getString("EST");
                String Prod_Name = rs.getString("Prod_Name");
                String Prod_Code = rs.getString("Prod_Code");
                
                
                String p = UPC_Code_col + " " + Manu_Info + " " + Date_Found + " " + EST + " " + Prod_Name + " " + Prod_Code;
                System.out.println(p);
     }
           
     }  
    catch ( SQLException err ) {
        JOptionPane.showMessageDialog(Products.this, err.getMessage( ) );
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        Man = new javax.swing.JTextField();
        UPC = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Est = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Manufacturer");

        label2.setText("UPC Code");

        label3.setText("Establishment");

        label4.setText("Date Found");

        label5.setText("Product Name");

        label6.setText("Product Code");

        Man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManActionPerformed(evt);
            }
        });

        UPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPCActionPerformed(evt);
            }
        });

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstActionPerformed(evt);
            }
        });

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panel1Layout = new org.jdesktop.layout.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(label5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(panel1Layout.createSequentialGroup()
                            .add(label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(UPC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, panel1Layout.createSequentialGroup()
                            .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(Man, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(label3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(panel1Layout.createSequentialGroup()
                        .add(Est, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel1Layout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(label4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(panel1Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(label6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 14, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(code, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Man, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(panel1Layout.createSequentialGroup()
                        .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(panel1Layout.createSequentialGroup()
                                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(UPC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(11, 11, 11)
                                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(label3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(label5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, panel1Layout.createSequentialGroup()
                                .add(label6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(code, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(2, 2, 2)
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Est, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setText("Update Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(10, 60, 135, 29);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Cancel New Record");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(170, 60, 164, 29);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(370, 60, 75, 29);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("New Record");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(20, 20, 110, 29);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("Save New Record");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(170, 20, 130, 29);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton10.setLabel("Delete Record");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jButton10.setBounds(315, 20, 120, 29);
        jLayeredPane1.add(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText("First");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(0, 20, 75, 29);
        jLayeredPane2.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setText("Previous");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.setBounds(110, 20, 97, 29);
        jLayeredPane2.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton8.setText("Next");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.setBounds(220, 20, 75, 29);
        jLayeredPane2.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setText("Last");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setBounds(330, 20, 75, 29);
        jLayeredPane2.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLayeredPane1)
                    .add(jLayeredPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 33, Short.MAX_VALUE)
                .add(jLayeredPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// cancel button
    try {
        rs.absolute(curRow);
        textManu_Info.setText(rs.getString("Manu_Info"));
        textDate_Found.setText(rs.getString("Date_Found"));
        textEST.setText(rs.getString("EST"));
        textProd_Code.setText(rs.getString("Prod_Code"));
        textProd_Name.setText(rs.getString("Prod_Name"));
        textUPC_Code.setText( Integer.toString(rs.getInt("UPC_Code")) );
        
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton1.setEnabled(true);
        jButton10.setEnabled(true);
        jButton1.setEnabled(true);
        
        jButton5.setEnabled(false);
        jButton2.setEnabled(false);        
        
        
    }
    catch (SQLException err) {
        System.out.println(err.getMessage());
    }
        Man.setText("");
        UPC.setText("");
        Date.setText("");
        name.setText("");
        Est.setText("");
        code.setText("");
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    System.exit(0);        // exit button
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    //new record button
    try {
        curRow = rs.getRow();
        
        textManu_Info.setText("");
        textUPC_Code.setText("");
        textDate_Found.setText("");
        textEST.setText("");
        textProd_Name.setText("");
        textProd_Code.setText("");
       
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton1.setEnabled(true);
        jButton10.setEnabled(true);
        jButton1.setEnabled(true);
        
        jButton5.setEnabled(false);
        jButton2.setEnabled(false);        
        
        
}
catch (SQLException err) {
    System.out.println(err.getMessage());
    
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //update button
    String Manu_Info = textManu_Info.getText();
    String Date = textDate_Found.getText();
    String EST = textEST.getText();
    String Prod_Name = textProd_Name.getText();
    String Prod_Code = textProd_Code.getText();
    String UPC_Code = textUPC_Code.getText();
    
    int newUPC_Code = Integer.parseInt(UPC_Code);
    
    try {
        rs.updateInt("UPC_Code", newUPC_Code);
        rs.updateString("Manu_Info", Manu_Info);
        rs.updateString("Date_Found", Date);
        rs.updateString("EST", EST);
        rs.updateString("Prod_Name", Prod_Name);
        rs.updateString("Prod_Code", Prod_Code);
        rs.updateRow();
        JOptionPane.showMessageDialog(Products.this, "Updated");
    }
    catch (SQLException err) {
        System.out.println(err.getMessage());
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // save new record button
        String Manu_Info = textManu_Info.getText();
        String Date_Found = textDate_Found.getText();
        String EST = textEST.getText();
        String Prod_Code = textProd_Code.getText();
        String Prod_Name = textProd_Name.getText();
        String UPC_Code = textUPC_Code.getText();
        int newUPC_Code = Integer.parseInt(UPC_Code);
        
        try {
            rs.moveToInsertRow();
            
            rs.updateInt("UPC_Code", newUPC_Code);
            rs.updateString("Manu_Info", Manu_Info);
            rs.updateString("Date_Found", Date_Found);
            rs.updateString("EST", EST);
            rs.updateString("Prod_Code", Prod_Code);
            rs.updateString("Prod_Name", Prod_Name);
            
            rs.insertRow();
            
            stmt.close();
            rs.close();
            
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM PROD_DESC";
            rs = stmt.executeQuery(sql);
            
            rs.next();
            int UPC_Code_col = rs.getInt("UPC_Code");
            String UPC_Code2 = Integer.toString(UPC_Code_col);
            String Manu_Info2 = rs.getString("Manu_Info");
            String Date_Found2 = rs.getString("Date_Found");
            String EST2 = rs.getString("EST");
            String Prod_Code2 = rs.getString("Prod_Code");
            String Prod_Name2 = rs.getString("Prod_Name");
            
            textUPC_Code.setText(UPC_Code);
            textManu_Info.setText(Manu_Info2);
            textDate_Found.setText(Date_Found2);
            textEST.setText(EST2);
            textProd_Code.setText(Prod_Code2);
            textProd_Name.setText(Prod_Name2);
            
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton8.setEnabled(true);
            jButton9.setEnabled(true);
            jButton1.setEnabled(true);
            jButton10.setEnabled(true);
            jButton1.setEnabled(true);
        
            jButton5.setEnabled(false);
            jButton2.setEnabled(false);
            
        }
        catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    try {   //next button
        if (rs.next()) {
            int UPC_Code_col = rs.getInt("UPC_Code");
            String UPC_Code = Integer.toString(UPC_Code_col);
            String Manu_Info = rs.getString("Manu_Info");
            String Date_Found = rs.getString("Date_Found");
            String EST = rs.getString("EST");
            String Prod_Code = rs.getString("Prod_Code");
            String Prod_Name = rs.getString("Prod_Name");
            
            textUPC_Code.setText(UPC_Code);
            textManu_Info.setText(Manu_Info);
            textDate_Found.setText(Date_Found);
            textEST.setText(EST);
            textProd_Code.setText(Prod_Code);
            textProd_Name.setText(Prod_Name);
            
        }
        else {
          rs.previous();
          JOptionPane.showMessageDialog(Products.this, "End of File");
        }
    }
    catch (SQLException err) {
    JOptionPane.showMessageDialog(Products.this, err.getMessage());

    }//GEN-LAST:event_jButton8ActionPerformed
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {   //Previous button
        if (rs.previous()) {
            int UPC_Code_col = rs.getInt("UPC_Code");
            String UPC_Code = Integer.toString(UPC_Code_col);
            String Manu_Info = rs.getString("Manu_Info");
            String Date_Found = rs.getString("Date_Found");
            String EST = rs.getString("EST");
            String Prod_Code = rs.getString("Prod_Code");
            String Prod_Name = rs.getString("Prod_Name");
            
            textUPC_Code.setText(UPC_Code);
            textManu_Info.setText(Manu_Info);
            textDate_Found.setText(Date_Found);
            textEST.setText(EST);
            textProd_Code.setText(Prod_Code);
            textProd_Name.setText(Prod_Name);
            
        }
        else {
          rs.next();
          JOptionPane.showMessageDialog(Products.this, "End of File");
        }
    }
  
    catch (SQLException err) {
    JOptionPane.showMessageDialog(Products.this, err.getMessage());
    }//GEN-LAST:event_jButton7ActionPerformed
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // First Button
        try {
            rs.first();
            int UPC_Code_col = rs.getInt("UPC_Code");
            String UPC_Code = Integer.toString(UPC_Code_col);
            String Manu_Info = rs.getString("Manu_Info");
            String Date_Found = rs.getString("Date_Found");
            String EST = rs.getString("EST");
            String Prod_Code = rs.getString("Prod_Code");
            String Prod_Name = rs.getString("Prod_Name");
            
            textUPC_Code.setText(UPC_Code);
            textManu_Info.setText(Manu_Info);
            textDate_Found.setText(Date_Found);
            textEST.setText(EST);
            textProd_Code.setText(Prod_Code);
            textProd_Name.setText(Prod_Name);
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(Products.this, err.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {   // last button
            rs.last();
            int UPC_Code_col = rs.getInt("UPC_Code");
            String UPC_Code = Integer.toString(UPC_Code_col);
            String Manu_Info = rs.getString("Manu_Info");
            String Date_Found = rs.getString("Date_Found");
            String EST = rs.getString("EST");
            String Prod_Code = rs.getString("Prod_Code");
            String Prod_Name = rs.getString("Prod_Name");
            
            textUPC_Code.setText(UPC_Code);
            textManu_Info.setText(Manu_Info);
            textDate_Found.setText(Date_Found);
            textEST.setText(EST);
            textProd_Code.setText(Prod_Code);
            textProd_Name.setText(Prod_Name);
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(Products.this, err.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // delete record button
try {
    rs.deleteRow();
    stmt.close();
    rs.close();
    stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    String sql = "SELECT * FROM PROD_DESC";
    rs = stmt.executeQuery(sql);
    
    
    rs.next();
    int UPC_Code_col = rs.getInt("UPC_Code");
    String UPC_Code = Integer.toString(UPC_Code_col);
    String Manu_Info = rs.getString("Manu_Info");
    String Date_Found = rs.getString("Date_Found");
    String EST = rs.getString("EST");
    String Prod_Code = rs.getString("Prod_Code");
    String Prod_Name = rs.getString("Prod_Name");
    
    
    textUPC_Code.setText(UPC_Code);
    textManu_Info.setText(Manu_Info);
    textDate_Found.setText(Date_Found);
    textEST.setText(EST);
    textProd_Code.setText(Prod_Code);
    textProd_Name.setText(Prod_Name);
    
}
catch (SQLException err) {
    JOptionPane.showMessageDialog(Products.this, err.getMessage() );
}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // Product name text bock
    }//GEN-LAST:event_nameActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // Product code text block
    }//GEN-LAST:event_codeActionPerformed

    private void EstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstActionPerformed
        // establishment text block
    }//GEN-LAST:event_EstActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // Date found text block
    }//GEN-LAST:event_DateActionPerformed

    private void UPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPCActionPerformed
        // UPC text block
    }//GEN-LAST:event_UPCActionPerformed

    private void ManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManActionPerformed
        // Manufacturer text block
    }//GEN-LAST:event_ManActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Products().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Est;
    private javax.swing.JTextField Man;
    private javax.swing.JTextField UPC;
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JTextField name;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
